apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  template:
    spec:
      containers:
        - name: console
          args:
            - --port=:8443
            - --base-url=https://localhost:30443
            - --apiserver-endpoint=https://local-k8s.dj-kubelet.com:6443
            - --cert-file=/etc/tls/tls.crt
            - --key-file=/etc/tls/tls.key
            - --secret-name=spotify-oauth
