apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauther
  name: oauther
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauther
  template:
    metadata:
      labels:
        app: oauther
    spec:
      serviceAccountName: oauther
      securityContext:
        runAsNonRoot: true
        runAsUser: 65535
        runAsGroup: 65535
        fsGroup: 65535

      containers:
      - image: djkubelet/spotify-oauther:latest
        name: spotify-oauther
        imagePullPolicy: IfNotPresent
        args:
        - --tls=true
        - --port=:8443
        - --base-url=https://localhost:8443
        - --cert-file=/etc/tls/tls.crt
        - --key-file=/etc/tls/tls.key
        - --secret-name=spotify-oauth
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauther
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauther
              key: CLIENT_SECRET
        volumeMounts:
        - name: server-tls
          mountPath: "/etc/tls"
        securityContext:
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
      volumes:
      - name: server-tls
        secret:
          secretName: server-tls
