apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauther
  namespace: oauther

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oauth-refresher
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oauth-refresher
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - create

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - patch
  resourceNames:
  - spotify-oauth

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oauther
  namespace: default
subjects:
- kind: ServiceAccount
  name: oauther
  namespace: oauther
roleRef:
  kind: Role
  name: oauth-refresher
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oauther-cluster
subjects:
- kind: ServiceAccount
  name: oauther
  namespace: oauther
roleRef:
  kind: ClusterRole
  name: oauth-refresher
  apiGroup: rbac.authorization.k8s.io
