apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base

namespace: console

secretGenerator:
- name: console
  env: envfile
  behavior: merge
  type: Opaque
- name: server-tls
  type: "kubernetes.io/tls"
  files:
    - tls.crt=server.pem
    - tls.key=server-key.pem

patchesStrategicMerge:
- deployment-patch.yaml
