# This role gives users access to read cluster information
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dj-kubelet:user-global
rules:
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  verbs:
  - create

- nonResourceURLs:
  - /healthz
  - /version
  - /version/
  verbs:
  - get

---

# This role is bound in a namespaced RoleBinding so access is not granted
# to other namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dj-kubelet:user

rules:
- apiGroups: ["dj-kubelet.com"]
  resources:
  - tracks
  verbs:
  - get
  - list
  - watch
  - create
  - delete

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  resourceNames:
  - spotify-oauth
