apiVersion: v1
kind: Service
metadata:
  labels:
    app: console
  name: console
spec:
  type: NodePort
  selector:
    app: console
  ports:
  - name: https
    nodePort: 30443
    port: 30443
    protocol: TCP
    targetPort: 8443
